import matplotlib.pyplot as plt

def Single(x,y):
    plt.plot(x,y,color='black',  linestyle='solid', linewidth = 2.0, label='only water')
    #plt.plot(x3,y3,color='red',  linestyle='solid', linewidth = 2.0, label='water + PH3')
    #plt.plot(clf)
    plt.title('Potassium Hexacyanoferrate',fontsize=16)
    plt.xlabel('Wave Number [cm-1]',fontsize=16) 
    plt.ylabel('Singlebeam [%]',fontsize=16) 
    plt.xlim()
    plt.ylim()
    plt.grid(color='b', linestyle='--', linewidth=0.1)
    plt.legend()
    plt.show()

def Trans(x,y):
    plt.plot(x,y,color='black',  linestyle='solid', linewidth = 2.0, label='only water')
    #plt.plot(x3,y3,color='red',  linestyle='solid', linewidth = 2.0, label='water + PH3')
    #plt.plot(clf)
    plt.title('Potassium Hexacyanoferrate',fontsize=16)
    plt.xlabel('Wave Number [cm-1]',fontsize=16) 
    plt.ylabel('Transmittance [%]',fontsize=16) 
    plt.xlim()
    plt.ylim()
    plt.grid(color='b', linestyle='--', linewidth=0.1)
    plt.legend()
    plt.show()

def Abs(x,y,bkg,fix):
    #ax1 = plt.ubplot2grid((2,2), (0,0), colspan=5)
    #ax2 = plt.subplot2grid((2,2), (1,0), colspan=2)
    plt.plot(x, y, linewidth=2)
    plt.plot(x, bkg, "b", linewidth=1, linestyle = "dashed", label="baseline")
    #ax2.plot(x, fix, "r", linewidth=1, linestyle = "solid", label="remove baseline")
    plt.xlabel('Wave Number [cm-1]',fontsize=16) 
    plt.ylabel('Absorbance [%]',fontsize=16) 
    plt.xlim()
    plt.ylim()
    plt.grid(color='b', linestyle='--', linewidth=0.1)
    plt.legend()
    plt.show()
